### ISSUE TITLE
?Request?: Add Multi Language Support in client.

### ISSUE THREAD

**Issue by lordm0use** [cloudclientdev/cloudclient#36]
when i changed text from eng to ru language at titlescreen gui i'm started crashing.
Time: 1/29/23 4:35 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at dev.cloudmc.helpers.font.GlyphPage$Glyph.access$000(GlyphPage.java:192)
	at dev.cloudmc.helpers.font.GlyphPage.getWidth(GlyphPage.java:177)
	at dev.cloudmc.helpers.font.GlyphPageFontRenderer.getStringWidth(GlyphPageFontRenderer.java:368)
	at dev.cloudmc.gui.titlescreen.Button.renderButton(Button.java:52)
	at dev.cloudmc.gui.titlescreen.TitleScreen.func_73863_a(TitleScreen.java:55)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at dev.cloudmc.helpers.font.GlyphPage$Glyph.access$000(GlyphPage.java:192)
	at dev.cloudmc.helpers.font.GlyphPage.getWidth(GlyphPage.java:177)
	at dev.cloudmc.helpers.font.GlyphPageFontRenderer.getStringWidth(GlyphPageFontRenderer.java:368)
	at dev.cloudmc.gui.titlescreen.Button.renderButton(Button.java:52)
	at dev.cloudmc.gui.titlescreen.TitleScreen.func_73863_a(TitleScreen.java:55)

-- Screen render details --
Details:
	Screen name: dev.cloudmc.gui.titlescreen.TitleScreen
	Mouse location: Scaled: (0, 264). Absolute: (0, 0)
	Screen size: Scaled: (463, 265). Absolute: (925, 530). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by CodeKid0** [comment]
Currently, the custom font renderer does not support cyrillic characters.
